[package]
name = "polkadot-node-core-dispute-coordinator"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
futures = "0.3.12"
tracing = "0.1.26"
parity-scale-codec = "2"
kvdb = "0.9.0"
derive_more = "0.99.1"

polkadot-primitives = { path = "../../../primitives" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
kvdb-memorydb = "0.9.0"
